item icons
object-Object/HexMod pull request #7
Opened 2023-10-19 23:48 UTC by SamsTheNerd

2023-10-20 23:20 UTC, SamsTheNerd commented
adds item icons to the toc and section headers to match the patchouli entry/category icons.

also adds flaymind recipe cards. seems to work for 0.11 villagers + other entities, i imagine it *should* work with 0.10 villagers but I haven't had the chance to test it. It does not work for the EntityTagIngredient, but I don't think that's used by anything in hex yet.

2023-10-23 01:24 UTC, object-Object requested changes
good work! the mind flaying especially is very pretty. unfortunately i have many comments

2023-10-23 01:24 UTC, object-Object commented on doc/properties.toml
> +missing = [
very important update

2023-10-23 01:24 UTC, object-Object commented on doc/resources/assets/hexcasting/lang/en_us.flatten.json5
> +    villagerrequirements: {
nit: code style
```suggestion
    villager_requirements: {
```

2023-10-23 01:24 UTC, object-Object commented on doc/resources/assets/hexcasting/lang/en_us.flatten.json5
> +      professional: "Villager must be a {} {} or higher",
these should have names, like `Villager must be a {level} {profession} or higher`. then in the code you'd do `.format(level=..., profession=...)`

2023-10-23 01:24 UTC, object-Object commented on doc/resources/assets/minecraft/textures/entities/allay.png
nit: maybe we could add some empty margin around this to make it a more reasonable scale?

2023-10-23 01:24 UTC, object-Object commented on doc/resources/assets/minecraft/textures/entities/villagers/nitwit.png
just like me fr

2023-10-23 01:24 UTC, object-Object commented on doc/resources/assets/minecraft/textures/item/enchanted_book.png
this shouldn't need to exist, i'm sure it's in the existing textures. but i guess it's fine for now since i need to redo all that anyway

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/components/textures.jcss.jinja
> +      {{ frame.start_percent }}%, {{ frame.end_percent }}% { background-position-y: {{ -100 * frame.index}}% }
nit: code style
```suggestion
      {{ frame.start_percent }}%, {{ frame.end_percent }}% { background-position-y: {{ -100 * frame.index }}% }
```

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/formatting.html.jinja
> +{% macro render_icon(iconish, name="") -%}
```suggestion
{% macro render_icon(item_or_texture, name="") -%}
```

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/formatting.html.jinja
> +  <a href="#{{ value.id.path }}" class="toc-elem {{ ' spoilered'|safe if value.is_spoiler }}">{{ render_icon(value.icon) }} {{ value.name }}</a>
i'm *pretty* sure we don't need safe here now - there's nothing to escape anymore
```suggestion
  <a href="#{{ value.id.path }}" class="toc-elem{{ ' spoilered' if value.is_spoiler }}">{{ render_icon(value.icon) }} {{ value.name }}</a>
```

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +{% macro render_mindcipe(recipe) -%}
cute name! unfortunately i do want to lean more towards clarity over whimsy. maybe something like `brainsweep_recipe()` or `flay_mind_recipe()`? unsure

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +      {% for recipe in recipes %} #}
these should be removed if not needed

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +              alt="Mindflay recipe gui"
```suggestion
              alt="Flay Mind recipe GUI"
```

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +  {% endif %}
this logic should really be done on the python side imo, so we get full type checking etc. `set` should be an absolute last resort - python should do logic, jinja should stick to filling placeholders wherever possible

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +        _('entity.minecraft.villager.%s'|format(prof))
these, at least, could probably be done during pydantic validation

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +{# TODO: figure out how to handle this. I don't think it's used in anything rn ? #}
i think a giant hashtag symbol would be funny

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +  {% set entity = entity.entityType.path %}
this should also be a python property that returns the formatted resourcelocation. or even a texture

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/_templates/pages/hexcasting/brainsweep.html.jinja
> +  ) }} #}
remove if not needed (also - this is the last place `generic()` is used, so you can remove that entire macro if you want)

2023-10-23 01:24 UTC, object-Object commented on doc/src/hexdoc/hexcasting/hex_recipes.py
> +    block: ItemWithTexture
👍

2023-11-05 21:48 UTC, SamsTheNerd commented
ok, went through and did some of the changes.

didn't do allay resize or the move to python stuff. 

i agree a giant hashtag would be funny lol.

2023-11-05 23:04 UTC, object-Object requested changes

2023-11-05 23:04 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/formatting.html.jinja
> +  <a href="#{{ value.id.path }}" class="toc-elem {{ ' spoilered' if value.is_spoiler }}">{{ render_icon(value.icon) }} {{ value.name }}</a>
nit:
```suggestion
  <a href="#{{ value.id.path }}" class="toc-elem {{ 'spoilered' if value.is_spoiler }}">{{ render_icon(value.icon) }} {{ value.name }}</a>
```

2023-11-05 23:04 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +{# rip render_mindcipe(), you will be missed :tear_emoji:  #}
pensive

2023-11-05 23:04 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +        level=_('merchant.level.%d'|format(villager.minLevel) ),
i'm *fairly* sure this works? if so, i think it looks a lot clearer
```suggestion
        level=_('merchant.level.'~villager.minLevel),
```

2023-11-05 23:04 UTC, object-Object commented on doc/src/hexdoc/_templates/macros/recipes.html.jinja
> +        level=_('merchant.level.%d'|format(villager.minLevel) ),
wait, why is it `minLevel`? everything should be camel case

2023-11-05 23:24 UTC, object-Object approved these changes

2023-11-05 23:24 UTC, object-Object commented
thanks!

2023-11-06 01:25 UTC, object-Object commented
HexMod: https://github.com/object-Object/HexMod/compare/f229e4f8ae178f54ccae9a046551d8d2e0643e45...e332cfdb468c261c0277560bfccd1647c3490701
hexdoc: https://github.com/object-Object/hexdoc/commit/7202a5c1030ae9a3087acfc4b0cbf40eb7593653

(they did surgery on a git repo)

2023-11-06 01:25 UTC, closed without merging